export default {
  LOAD_DATA: "LOAD_DATA",
  MOTHER_INPUT: "MOTHER_INPUT",
  FATHER_INPUT: "FATHER_INPUT",
  BOTH_PARENTS: "BOTH_PARENTS",
  DESCENDANT_INPUT: "DESCENDANT_INPUT",
  SIBLING_NAME_SEARCH: "SIBLING_NAME_SEARCH",
};
